name: aqua

permissions: {}

on:
  pull_request:
    branches: ["main"]
    paths:
      - aqua.yaml
      - aqua-checksums.json
      - .github/workflows/aqua.yml

jobs:
  aqua:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 20
    steps:
    - uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1.11.6
      id: app-token
      with:
        app-id: ${{ vars.TAGPR_GITHUB_APP_ID }}
        private-key: ${{ secrets.TAGPR_GITHUB_APP_PRIVATE_KEY }}
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        token: ${{ steps.app-token.outputs.token }}
        persist-credentials: false
    - uses: aquaproj/aqua-installer@d1fe50798dbadd4eb5b98957290ca175f6b4870f # v4.0.2
      with:
        aqua_version: v2.53.5
    - uses: aquaproj/update-checksum-action@2fb7f676d407d4fb8c2c466c19d09d3ddec4f82f # v0.2.2
      with:
        prune: true
      env:
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
